spring.datasource.url: jdbc:mysql://localhost:3306/blogs?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: valery_56
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false

blog.title: Developers Stories
blog.subtitle: Истории разработчиков
blog.phone: +7 999 111-22-33
blog.email: rokotov@tiptop.pl
blog.copyright: George Rokotoff
blog.copyrightFrom: 2020