#spring.datasource.url: jdbc:mysql://localhost:3306/booklib
#spring.datasource.username: root
#spring.datasource.password: %Remen_56#
#spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booklib
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:localhost:3306/booklib; DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: %Remen_56#
spring.jpa.hibernate.ddl-auto: create
someParameter:
   value: 5463



