#spring.datasource.url: jdbc:mysql://localhost:3306/booklib
#spring.datasource.username: root
#spring.datasource.password: 12345678
#spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booklib
    username: root
    password: 12345678
spring.jpa.hibernate.ddl-auto: create
someParameter:
  value: 5463
